# Generated by Django 3.2.2 on 2021-05-10 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tank_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tankevent',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tankevent',
            name='petrol_quantity_liter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tankevent',
            name='petrol_station',
            field=models.CharField(choices=[('mol', 'MOL'), ('shell', 'SHELL'), ('omv', 'OMV')], default='mol', max_length=20),
        ),
        migrations.AddField(
            model_name='tankevent',
            name='petrol_type',
            field=models.CharField(choices=[('gasoline95', 'BENZIN-95'), ('gasoline100', 'BENZIN-100'), ('diesel', 'DIZEL')], default='gasoline95', max_length=20),
        ),
        migrations.AddField(
            model_name='tankevent',
            name='price_ft',
            field=models.FloatField(default=0.0),
        ),
    ]
