# Generated by Django 3.2.2 on 2021-05-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank_api', '0002_auto_20210510_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankevent',
            name='name',
        ),
    ]
