# Generated by Django 3.2.2 on 2021-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(default=0)),
                ('petrol_type', models.CharField(choices=[('gasoline95', 'BENZIN-95'), ('gasoline100', 'BENZIN-100'), ('diesel', 'DIZEL')], default='gasoline95', max_length=20)),
                ('petrol_station', models.CharField(choices=[('mol', 'MOL'), ('shell', 'SHELL'), ('omv', 'OMV')], default='mol', max_length=20)),
                ('petrol_quantity_liter', models.FloatField(default=0.0)),
                ('price_ft', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
