# Generated by Django 3.2.2 on 2021-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(default=0)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tankevent',
            name='petrol_station',
            field=models.CharField(choices=[('mol', 'MOL'), ('shell', 'Shell'), ('omv', 'OMV')], default='mol', max_length=20),
        ),
        migrations.AlterField(
            model_name='tankevent',
            name='petrol_type',
            field=models.CharField(choices=[('gasoline95', '95-ös benzin'), ('gasoline100', '100-as benzin'), ('diesel', 'dízel')], default='gasoline95', max_length=20),
        ),
    ]
