# Generated by Django 3.2.2 on 2021-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_logic', '0002_auto_20210512_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='price_ft',
            field=models.FloatField(default=0.0),
        ),
    ]
